### ISSUE TITLE
Question: Is thera a way to transform uuid6 or uuid7 into datetime?

### ISSUE THREAD

**Issue by edelvalle** [oittaa/uuid6-python#28]
Since the value of there UUIDs is derived from time, is there a way to transform it back into datetime?

**Comment by oittaa** [comment]
There's a `.time` property just like the of standard UUID module has it for UUID v1, which returns the timestamp as an integer. You have to use one of the `datetime` methods afterwards to convert it to a `datetime` though. UUID v6 uses the same offset as the standard UUID v1. UUID v7 epoch is the same as Unix epoch.

You can check couple of examples from the tests: https://github.com/oittaa/uuid6-python/blob/dc979a671f4a9112ad0cf1c7850aad8fbb169bde/test/test_uuid6.py#L105-L125

**Comment by oittaa** [comment]
Something like this

```
import datetime
import uuid6

uuid_7 = uuid6.uuid7()
unixts, nanos = divmod(uuid_7.time, 10**9)
dt = datetime.datetime.utcfromtimestamp(unixts) + datetime.timedelta(microseconds=nanos//1000)

print(dt)
```

**Comment by edelvalle** [comment]
Wow this is amazing! Thanks a lot

**Comment by venteto** [comment]
I tried using the above example to solve my own issue with a Django model, but I must be doing something wrong.

Here is my code in one of my models:

```python
    import datetime, uuid6

    def date_added_from_uuid7(self):
        # uuid_7 = uuid6.uuid7()
        uuid_7 = self.id

        unixts, nanos = divmod(uuid_7.time, 10**9)

        dtp = datetime.datetime.utcfromtimestamp(unixts) + \
            datetime.timedelta(microseconds=nanos//1000)

        dt = dtp.strftime("%Y-%m-%d")
        return dt
```

When I use the `uuid_7 = uuid6.uuid7()` value as provided in the example, the date returned is **1970-01-01**

When I use my actual `self.id`, the date returned is **2005-10-04** but the date expected was **2023-05-30**, which is set in a separate `date_added` column that I am hoping to get rid of, since I have the uuid7 `id` column already
